### ISSUE TITLE
Issue with spaces in usernames

### ISSUE THREAD

**Issue by eeeAAAkkk** [qlaffont/fortnite-api#125]
Hey there,

I saw that someone else also had problems with spaces in usernames but didn't provide the solution and my problem looks a bit different.

```
fortniteAPI.login().then(() => {
	      fortniteAPI
	          .getStatsBR("FaZe Mew", "pc", "weekly")
	          .then(stats => {
	              console.log(stats);
	          })
	          .catch(err => {
	              console.log(err);
	          });
	  });
```

Here are my errors that I receive. Calls with other usernames work.

```
TypeError: Cannot read property 'every' of undefined
    at Object.checkPlatform (/home/whatever/node_modules/fortnite-api/tools/stats.js:28:15)
    at request.then.stats (/home/whatever/node_modules/fortnite-api/index.js:245:39)
    at tryCatcher (/home/whatever/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/whatever/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/whatever/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/whatever/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/whatever/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/whatever/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/whatever/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/whatever/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/whatever/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

Thanks for your help.

**Comment by eeeAAAkkk** [comment]
Same issue with special characters.

**Comment by qlaffont** [comment]
I have fixed the error. You can try again.

**Comment by eeeAAAkkk** [comment]
Thank you!

Another question that is not related to your API but you have a better understanding of the Epic API. I try to get stats for userid 6598b2dfe72c48ee94068fb39dc1ff9b. The lookup works but I don't get any stats - only for that user. Tried to grab with name and id.

**Comment by RobertoGraham** [comment]
@eeeAAAkkk Similar/same issue discussed [here](https://github.com/Tustin/fortnite-php/issues/43). Resolved by changing leader board privacy settings.
