### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Vanerac** [qlaffont/fortnite-api#129]
```
{ StatusCodeError: 403 - {"errorCode":"errors.com.epicgames.common.missing_action","errorMessage":"Login is banned or does not posses the action 'PLAY' needed to perform the requested operation for platform ''","messageVars":["PLAY",""],"nu
mericErrorCode":1023,"originatingService":"fortnite","intent":"prod-live"}
    at new StatusCodeError (C:\Users\Corentin\OneDrive\Projets\En Cours\Github\Drake\Bot-Drake\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\Corentin\OneDrive\Projets\En Cours\Github\Drake\Bot-Drake\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\Corentin\OneDrive\Projets\En Cours\Github\Drake\Bot-Drake\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\Corentin\OneDrive\Projets\En Cours\Github\Drake\Bot-Drake\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Corentin\OneDrive\Projets\En Cours\Github\Drake\Bot-Drake\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Corentin\OneDrive\Projets\En Cours\Github\Drake\Bot-Drake\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by qlaffont** [comment]
Have you try to play one game with your account. Just to be sure that you didn't have any problem and your are not ban ?

**Comment by Vanerac** [comment]
Updated my game, started it,verifed login and passwd , restarted code, same error, not banned and i have the stw

**Comment by qlaffont** [comment]
Can you try to reverse your two token ? "Mzh" before "ZW"

**Comment by Vanerac** [comment]
yup that fixed it
