### ISSUE TITLE
Unexisting users?

### ISSUE THREAD

**Issue by Uniixx** [qlaffont/fortnite-api#131]
TypeError: Cannot read property 'every' of undefined
    at Object.checkPlatform (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\fortnite-api\tools\stats.js:28:15)
    at request.then.stats (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\fortnite-api\index.js:245:39)
    at tryCatcher (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Nathan\Desktop\Fortnite_QC\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

It is working fine, but some users throw errors like they are not existing or something.. but they do exists.

**Comment by monkeydioude** [comment]
Probably people having their account set to private

**Comment by Uniixx** [comment]
I don't know I mean you can check JayBrainDead with the API it doesn't work.. but on FortniteMaster, FortniteTracker It works fine.

**Comment by qlaffont** [comment]
Can you give me the user please and platform. I will check.

**Comment by monkeydioude** [comment]
FortniteTracker has some esoteric ways to get stats, we had case where people in private mode could not be found through this API but FortniteTracker could.
I believe that's the same for Reginald's baby

**Comment by iXyles** [comment]
A person is : avenger444 @ pc

**Comment by qlaffont** [comment]
For me the pseudo is not good. I have no data from Epic Games.

**Comment by iXyles** [comment]
I do understand that this issue is closed, even though this is an issue which has started to happen to a couple of people I know now. We can get the ID of the user but the not the stats anymore (suddenly)
Examples : Aerik_ , avenger444(as told before), wolf592, GreenMario3305 (probably goes on..) 

Does anyone have any information why it suddenly have stopped working with a few people but not all? Have they maybe added in some "privacy" setting or changed something with the endpoint? Then the question is why fortnitetracker/fortnitemaster is not affected or if they are using some other "connection" or if they might have gotten a "bearer" code to get more information or having higher permission?

**Comment by iXyles** [comment]
Okey, it seems Fortnite has added an option "Settings > Account > Leaderboard Privacy" which makes it impossible to retrieve the information through their "public" api, but fortnitetracker and fortnitemaster are still able to get the information somehow. (end of story I guess)

**Comment by monkeydioude** [comment]
Yeah, it has been said just above in this issue: https://github.com/qlaffont/fortnite-api/issues/131#issuecomment-424317597
