### ISSUE TITLE
Default tokens don't work anymore [BUG]

### ISSUE THREAD

**Issue by Volshebniqq** [qlaffont/fortnite-api#197]
These tokens provided in repo's readme doesn't work anymore:
"CLIENT LAUNCHER TOKEN" => "MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE="

"FORTNITE CLIENT TOKEN" => "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="

Error message: "Please enter good credentials (Login/Username/Launcher Token)".

The account's password and username remained the same.

Full error message:

Error: {"message":"Please enter good credentials (Login/Username/Launcher Token)","err":{"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (E:\\novos-graphql-server\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (E:\\novos-graphql-server\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (E:\\novos-graphql-server\\node_modules\\axios\\lib\\adapters\\http.js:237:11)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:448:20)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","config":{"url":"https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token","method":"post","data":"grant_type=password&username=myaccount&password=mypassword&includePerms=true","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","Authorization":"basic MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=","User-Agent":"axios/0.19.0","Content-Length":75},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}}

**Comment by juanpablofortnite** [comment]
any token that works for my php code?  https://i.imgur.com/CAdaoO8.png


Do you think this php code works if I get the token?

**Comment by Fyb3roptik** [comment]
The fortnite API endpoints have changed. Check my fork of this repo for the working copy
